version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eugeney
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pg 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eugeney -d pg"] 
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: